name: Build and Deploy Spring Boot Application v4

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/blog-apis:latest

  deploy:
    name: Deploy to VM
    runs-on: self-hosted
    needs: build-and-push-docker
    steps:
      - name: Pull Docker Image and Run Container
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/blog-apis:latest
          
          docker stop blog-apis-container || true
          docker rm blog-apis-container || true
          
          docker run -d \
            --name blog-apis-container \
            -p 8080:8080 \
            ${{ secrets.DOCKER_HUB_USERNAME }}/blog-apis:latest
